# https://jekyllrb.com/docs/configuration

# Handling Reading
encoding: utf-8
exclude: [
  "CNAME",
  "Gemfile",
  "Gemfile.lock",
  "Procfile",
  "README",
  "sass",
  "scripts",
  ".travis.yml",
  ".ruby-version",
  "_config.yml"
]



# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap


# Outputting
permalink: /:year/:month/:title.html
timezone: Europe/London


# Conversion
Markdown: kramdown

# Serving
port: 7777

# Meta
author: Rey Dhuny
description: This is a tagline
title : This is my homepage
url : http://reyhan.org
feed:
  path: atom.xml
